routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index')->name('home');
Route::get('post/{id}','HomeController@categoryWisePost')->name('post');

Auth::routes();
Route::group(['middleware'=>'auth'], function(){
    Route::get('/dashboard','Admin\DashboardController@index')->name('dashboard');
    Route::resource('/category','Admin\CategoryController');
    Route::resource('/post','Admin\PostController');
    Route::resource('/profile','Admin\UserController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function category(){
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Post;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $viewPage = 'admin.post.';

    public function index()
    {
        $posts = Post::all();
//        dd($posts);
        return view($this->viewPage.'index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view($this->viewPage.'create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'category_id' => 'required',
            'title' => 'required',
        ],
            [
                'category_id.required' => 'Category Name must not be empty!',
                'title.required' => 'Post Title must not be empty!',
            ]);

        if ($validator->fails()) {
            Session::flash('error', $validator->messages()->first());
            return redirect()->back()->withInput();
        }
        //$image = $request->file('image');

        //$name = 'orgd150718.png';
        if($request->file('image')!=null && $request->file('image')->isValid()) {
            try {
                $file = $request->file('image');
                $tempName = strtolower(str_replace(' ', '', $request->input('title')));
                $name = $tempName.date("dmy").'.' . $file->getClientOriginalExtension();

                $request->file('image')->move("images/post", $name);
            } catch (Illuminate\Filesystem\FileNotFoundException $e) {
//                    return false;
            }
        }
        $postImage = '';
        if(!empty($name)){
            $postImage = "images/post/".$name;
        }

        $post = new Post();

        $post->category_id = $request->category_id;
        $post->title = $request->title;
        $post->image = $postImage;
        $post->description = $request->description;
        $post->status = $request->status;

        $post->save();

        return redirect()->back()->with('success','Post created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
//        dd($post);
        return view($this->viewPage.'show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $post = Post::findOrFail($id);
        return view($this->viewPage.'edit',compact('post','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'category_id' => 'required',
            'title' => 'required',
        ],
            [
                'category_id.required' => 'Category Name must not be empty!',
                'title.required' => 'Post Title must not be empty!',
            ]);

        if ($validator->fails()) {
            Session::flash('error', $validator->messages()->first());
            return redirect()->back()->withInput();
        }
        //$image = $request->file('image');

        //$name = 'orgd150718.png';
        if($request->file('image')!=null && $request->file('image')->isValid()) {
            try {
                $file = $request->file('image');
                $tempName = strtolower(str_replace(' ', '', $request->input('title')));
                $name = $tempName.date("dmy").'.' . $file->getClientOriginalExtension();

                $request->file('image')->move("images/post", $name);
            } catch (Illuminate\Filesystem\FileNotFoundException $e) {
//                    return false;
            }
        }
        $postImage = '';
        if(!empty($name)){
            $postImage = "images/post/".$name;
        }else{
            $postImage = $request->input('editImage');
        }

        $post = Post::findOrFail($id);

        $post->category_id = $request->category_id;
        $post->title = $request->title;
        $post->image = $postImage;
        $post->description = $request->description;
        $post->status = $request->status;

        $post->save();

        return redirect()->back()->with('success','Post created successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/post/create.blade.php
@extends('layout.backend.app')
<style>
    .ck-editor__editable_inline {
        min-height: 300px;
    }
</style>
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary float-left">Add New Post</h4>
            <a href="{{ route('post.index') }}" class="btn btn-danger float-right"><i class="fa fa-arrow-left" aria-hidden="true"></i> Go Back</a>
        </div>
        <div class="card-body">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif

            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="category">Category Name</label>
                    <select class="form-control" id="category" name="category_id">
                        <option>Select One</option>
                        @foreach($categories as $row)
                        <option value="{{ $row->id }}">{{ $row->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Example: Post One Title Goes Here" name="title">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" class="form-control-file" id="image" name="image">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control ck-editor__editable_inline" name="description" id="editor"></textarea>
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select class="form-control" id="status" name="status">
                        <option value="0">Active</option>
                        <option value="1">Inactive</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );

    </script>
@endsection

resources/views/admin/post/edit.blade.php
@extends('layout.backend.app')
<style>
    .ck-editor__editable_inline {
        min-height: 300px;
    }
</style>
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary float-left">Edit Post</h4>
            <a href="{{ route('post.index') }}" class="btn btn-danger float-right"><i class="fa fa-arrow-left" aria-hidden="true"></i> Go Back</a>
        </div>
        <div class="card-body">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif

            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            <form action="{{ route('post.update',$post->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="category">Category Name</label>
                    <select class="form-control" id="category" name="category_id">
                        <option>Select One</option>
                        @foreach($categories as $row)
                            <option value="{{ $row->id }}" @if($post->category_id == $row->id) selected @endif>{{ $row->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Example: Post One Title Goes Here" name="title" value="{{ $post->title }}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="hidden" class="form-control-file" id="image" name="editImage" value="{{ $post->image }}">
                    <input type="file" class="form-control-file" id="image" name="image" onchange="readURL(this);"><br>
                    <img id="blah" src="{{ asset($post->image) }}" alt="your image" width="120" height="150"/>
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control ck-editor__editable_inline" name="description" id="editor">{!! $post->description !!}</textarea>
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select class="form-control" id="status" name="status">
                        <option value="0" @if($post->status == 0) selected @endif>Active</option>
                        <option value="1" @if($post->status == 1) selected @endif>Inactive</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(120)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

    </script>
@endsection

resources/views/admin/post/index.blade.php
@extends('layout.backend.app')

@section('content')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary float-left">Post</h4>
            <a href="{{ route('post.create') }}" class="btn btn-primary float-right"><i class="fa fa-plus-circle" aria-hidden="true"> </i> Add New</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th style="width: 30px;">SL</th>
                        <th style="width: 250px;">Category Name</th>
                        <th style="width: 100px;">Image</th>
                        <th>Title</th>
                        <th style="width: 40px;">Status</th>
                        <th style="width: 180px;">Action</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>SL</th>
                        <th>Category Name</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @php
                        $i = 0;
                    @endphp
                    @if(!$posts->isEmpty())
                        @foreach($posts as $row)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $row->category->name }}</td>
                                <td><img src="{{ $row->image }}" width="40" height="30"></td>
                                <td>{{ $row->title }}</td>
                                <td>
                                    @if($row->status == 0)
                                    <div class="p-1 bg-success text-white">Active</div>
                                    @else
                                    <div class="p-1 bg-danger text-white">Inactive</div>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('post.show',$row->id) }}" class="btn btn-primary btn-circle"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('post.edit',$row->id) }}" class="btn btn-primary btn-circle"><i class="fas fa-edit"></i></a>
                                    <form method="POST" action="{{ route('post.destroy', [$row->id]) }}" style="display:inline-block">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger btn-circle" type="submit"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6" style="text-align: center;">There is no data found</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/post/show.blade.php
@extends('layout.backend.app')

@section('content')

    <div class="row">
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary float-left">Show Post</h4>

                </div>
                <div class="card-body">
                    <span><b>Category Name: </b></span>
                    <span>{{ $post->category->name }}</span><br><br>
                    <span><b>Post Title: </b></span>
                    <span>{{ $post->title }}</span><br><br>
                    <span><b>Description: </b></span>
                    <span>{!! $post->description !!}</span>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary float-left">Show Post Image</h4>
                </div>
                <div class="card-body">
                    <img src="{{ asset($post->image) }}" width="200" height="200">
                </div>
            </div>
        </div>
    </div>





@endsection